- name: check if sdkman is installed
  shell: test -d {{sdkman.folder}} && echo "yes" || echo "no"
  register: is_sdkman_installed

- name: install SDKMAN!
  when: is_sdkman_installed.stdout == "no"
  shell: curl -s {{sdkman.install_url}} | bash executable=/bin/bash
  sudo: no

- name: ensure presence of .profile
  file: state=touch path={{general.local_home}}/.profile
  sudo: no

- name: Add sdkman in .profile
  lineinfile: dest={{general.local_home}}/.profile regexp="\/.sdkman/bin\/sdkman\-init\.sh" line='[[ -s "{{sdkman.folder}}/bin/sdkman-init.sh" && ! $(which sdkman-init.sh) ]] && source "{{sdkman.folder}}/bin/sdkman-init.sh"'
  sudo: no

- name: installing sdkman applications
  command: bash -lc "sdk install {{item}}"
  sudo: no
  with_items: "{{sdkman_applications}}"