- name: check if oh-my-fish is installed
  shell: test -d ~/.local/share/omf && echo "yes" || echo "no"
  register: is_ohmyfish_installed

- name: download oh-my-fish
  when: is_ohmyfish_installed.stdout == "no"
  get_url:
    url: https://get.oh-my.fish
    dest: "{{general.local_home}}/Downloads/fish_install"

- name: install oh-my-fish
  when: is_ohmyfish_installed.stdout == "no"
  shell: "fish {{general.local_home}}/Downloads/fish_install --noninteractive"
  sudo: no

- name: check if bobthefish is installed
  shell: test -d ~/.local/share/omf/themes/bobthefish && echo "yes" || echo "no"
  register: is_bobthefish_installed

- name: install bobthefish
  when: is_bobthefish_installed.stdout == "no"
  shell: echo "omf install bobthefish" | fish
  sudo: no

- name: fish config
  copy:
    src: dotfiles/omf.fish
    dest: "{{general.local_home}}/.config/fish/conf.d/omf.fish"