---
# list of applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

# homebrew applications
applications:
  - autojump
  - git
  - tree
  - httpie
  - curl
  - wget
  - zsh
  - go
  - vim
  - neovim

# homebrew cask applications
cask_applications:
  - google-chrome
  - docker