- name: dotfiles
  tags: dotfiles
  include: dotfiles.yml

- name: getting downloads
  tags: downloads
  get_url:
    url: "{{item.value.url}}"
    dest: "{{item.value.dest}}"
  with_dict: "{{downloads}}"