- name: dotfiles
  tags: dotfiles
  include: dotfiles.yml

- name: getting downloads
  tags: downloads
  get_url:
    url: "{{item.value.url}}"
    dest: "{{item.value.dest}}"
  with_dict: "{{downloads}}"

- name: install python packages
  tags: python
  pip:
    name: "{{item}}"
  with_items:
    - boto
    - boto3

# This task will fix an issue with IntelliJ being slow to start applications
- name: hosts file
  tags: hostsfile
  become: true
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1 localhost .*.local'
    line: "127.0.0.1 localhost {{ansible_hostname}}.local"
    owner: root
    group: wheel
    mode: 0644