- name: dotfiles
  tags: dotfiles
  include: dotfiles.yml

#- name: terminal
#  tags: terminal
#  include: terminal.yml

- name: getting downloads
  get_url:
    url: "{{item.value.url}}"
    dest: "{{item.value.dest}}"
  with_dict: "{{downloads}}"