---
- name: homebrew
  include: homebrew.yml

- name: sdkman
  include: sdkman.yml

- name: installing sdkman applications
  command: bash -lc "sdk install {{item}}"
  sudo: no
  with_items: "{{sdkman_applications}}"

- name: getting downloads
  get_url:
    url: "{{item.value.url}}"
    dest: "{{item.value.dest}}"
  with_dict: "{{downloads}}"

- name: start installing homebrew applications
  homebrew:
    name: "{{item}}"
    state: latest
  with_items: "{{applications}}"

- name: start installing homebrew cask applications
  homebrew_cask:
    name: "{{item}}"
    state: installed 
  with_items: "{{cask_applications}}"
