- name: dotfiles
  tags: dotfiles
  include: dotfiles.yml

- name: getting downloads
  get_url:
    url: "{{item.value.url}}"
    dest: "{{item.value.dest}}"
  with_dict: "{{downloads}}"

- name: configuration
  include: configuration.yml